FROM node

WORKDIR /voting

COPY ./package.json .
COPY ./packages/server/package.json ./packages/server/
COPY ./packages/common/package.json ./packages/common/


RUN yarn install --production

COPY ./packages/server/dist ./packages/server/  
COPY ./packages/common/dist ./packages/common/ 
COPY ./packages/server/.env.prod  ./packages/server/
COPY ./ormconfig.json .

WORKDIR ./packages/server

EXPOSE 80

CMD [ "node","dist/index.js" ]